### PR TITLE
Pool Table Page

### PR DESCRIPTION
**Pull request by pingustar**

### CODE REVIEW

**Comment by ashachaf** [comment]
- [ ] update top pools list
select top 20 token by APR where:
- pool is white listed
- liquidity is > 100000

**Comment by ashachaf** [comment]
@pingustar lets discuss few style updates
https://www.figma.com/file/fwADI9wqDrRAdlMX8EddCw/Bancor-v3?node-id=6533%3A184575

**Comment by ashachaf** [comment]
updated the doc with the items we have discussed.

**Comment by ashachaf** [comment]
desktop:
- [ ] stats arrow animation
please make it static or much much slower. it can jump up like you have it but every 15 seconds have it jump once.
 
- [ ] ticker title
current: Top Performing Pools
updated: Top Earners 

- [ ] table titles
current: Reward
updated: Rewards

- [ ] table font size
the "rewards" text is 12px instead of 14px. can you update it to 14px like all other cells in the table?

mobile:
- [ ] name columns is very wide. can we reduce width to fit 10 character pool name?
- [ ] i do not see the option to display more rows in the table in mobile. only the option to go to the next page. is this expected?

**Comment by pingustar** [comment]
- [ ] **Rewards Column:** 
- Align tooltip to left side
- Center rewards so that separators are all below each other


- [ ] **Add liquidity button should link to old app**
- open in new tab
- implement logic to decide wether to go to single side or dual liquidity


- [ ] **Top Pools: Add BNT**
- BNT APR will be based on the pool with highest BNT Rewards APR + Fees APR
- on click filter table to the pool with highest BNT APR


- [ ] **Remove Fee Column**

**Pull request merged**
