### PR TITLE
increase redux middleware warning to 128ms

### PR DESCRIPTION
**Pull request by pingustar**
this will remove the hundreds of warnings in dev mode

`SerializableStateInvariantMiddleware took 38ms, which is more than the warning threshold of 32ms. If your state or actions are very large, you may want to disable the middleware as it might cause too much of a slowdown in development mode. See https://redux-toolkit.js.org/api/getDefaultMiddleware for instructions. It is disabled in production builds, so you don't need to worry about that.`

### CODE REVIEW

**Comment by zavelevsky** [comment]
I think that we need to understand what exactly causes this (I believe it's the token list) and try to be as specific as possible with what we ignore (disable by state path, action type - if possible).

**Comment by pingustar** [comment]
> I think that we need to understand what exactly causes this (I believe it's the token list) and try to be as specific as possible with what we ignore (disable by state path, action type - if possible).

@zavelevsky I agree that we should follow up on the root problem. 

My suggestion is to open a new issue, proposing a real fix. Until then lets disable the warnings for now, as it floods the console and makes debugging harder.

As this change will have no further negative effect on production I think we should do it until we have a solution to close the issue indefinitely.

**Comment by zavelevsky** [comment]
> > I think that we need to understand what exactly causes this (I believe it's the token list) and try to be as specific as possible with what we ignore (disable by state path, action type - if possible).
> 
> @zavelevsky I agree that we should follow up on the root problem.
> 
> My suggestion is to open a new issue, proposing a real fix. Until then lets disable the warnings for now, as it floods the console and makes debugging harder.
> 
> As this change will have no further negative effect on production I think we should do it until we have a solution to close the issue indefinitely.

OK, but don't you think it's best to set instead `ignoredPaths` to the specific state paths that we know we need to ignore?

**Comment by pingustar** [comment]
> > > I think that we need to understand what exactly causes this (I believe it's the token list) and try to be as specific as possible with what we ignore (disable by state path, action type - if possible).
> > 
> > 
> > @zavelevsky I agree that we should follow up on the root problem.
> > My suggestion is to open a new issue, proposing a real fix. Until then lets disable the warnings for now, as it floods the console and makes debugging harder.
> > As this change will have no further negative effect on production I think we should do it until we have a solution to close the issue indefinitely.
> 
> OK, but don't you think it's best to set instead `ignoredPaths` to the specific state paths that we know we need to ignore?

added `ignoredPaths` for the tokens and tokenLists

**Review by zavelevsky — APPROVED** [review]
thanks!

**Pull request merged**
