### PR TITLE
GTM txHash

### LINKED ISSUE #547: google analytics - include tx hash
on the following events
Conversion Wallet Confirmed
Liquidity Deposit Wallet Confirmed

update to include tx hash
examples:
dataLayer.push({
  "event": "CE Conversion Wallet Confirmed",
  "event_properties": {
    **"transaction_hash": "0x838hrfi32872",**
    ...
    ...
    ...
  }
});

dataLayer.push({
  "event": "CE Liquidity Deposit Wallet Confirmed",
  "event_properties": {
    **"transaction_hash": "0x4kj3ke2jh3k24",**
    ...
    ...
    ...
  }
});

### PR DESCRIPTION
**Pull request by RanCohenn**
Fixes #547

### CODE REVIEW

**Review by zavelevsky — DISMISSED** [review]
LGTM

**Comment by ashachaf** [comment]
please make sure this data is part of the "event_properties"
image

**Comment by ashachaf** [comment]
can we confirm that we use the same name for this data?
current name: transaction_id
updated name: transaction_hash

**Comment by ashachaf** [comment]
please also include the "transaction_hash" data to the "wallet confirm" event

**Pull request merged**
