### PR TITLE
Limit Repairs

### PR DESCRIPTION
**Pull request by RanCohenn**

### CODE REVIEW

**Review by zavelevsky — APPROVED** [review]
LGTM

**Comment by ashachaf** [comment]
- [ ] load the preview url and click "limit". there is a console error and nothing happens. if you wait few seconds, it works fine.
Uncaught TypeError: Cannot read properties of undefined (reading 'address')
- [ ] wallet is not connected and there is a call to GET https://ropsten.etherscan.io/images/main/empty-token.png (return error 503)
- [ ] once you sign the limit order, you get 2 error notifications while the order is actually set (there is an open bug for this)

**Comment by pingustar** [comment]
503 error for empty-token image will be fixed with PR #543

**Comment by zavelevsky** [comment]
> * [ ]  load the preview url and click "limit". there is a console error and nothing happens. if you wait few seconds, it works fine.
>   Uncaught TypeError: Cannot read properties of undefined (reading 'address')

^ this also happens in production - I will fix in a separate PR

> * [ ]  wallet is not connected and there is a call to GET [ropsten.etherscan.io/images/main/empty-token.png](https://ropsten.etherscan.io/images/main/empty-token.png) (return error 503)

^ @pingustar fixed in a separate PR

> * [ ]  once you sign the limit order, you get 2 error notifications while the order is actually set (there is an open bug for this)

^ if there's a separate bug I will fix it in a separate PR

==> merging away

**Pull request merged**
