### PR TITLE
[Review/296] display pre suggested token list on token selection modal

### PR DESCRIPTION
**Pull request by pingustar**
comment at:

https://github.com/bancorprotocol/webapp-v2/pull/296 #204

### CODE REVIEW

**Comment by zavelevsky** [comment]
Awaiting the following fixes, commented on in #296 :

@baart1989

1. mouse over doesnt turn the cursor to clickable
2. mouse over effect isnt visible enough (both on light and dark modes)
3. case of ETH when the source token is ETH

plus, code comments: 

- https://github.com/bancorprotocol/webapp-v2/pull/296#discussion_r727815210
- https://github.com/bancorprotocol/webapp-v2/pull/296#discussion_r727811251

**Comment by Hadas-Bancor** [comment]
Screen Shot 2021-10-13 at 11 07 33

**Comment by ashachaf** [comment]
@zavelevsky i think we should take ownership of this and take it over the finish line.

**Comment by zavelevsky** [comment]
@pingustar please complete this according to the specs

**Comment by pingustar** [comment]
closing in favour of #485

**Pull request closed without merging**
