### PR TITLE
Balance update

### PR DESCRIPTION
**Pull request by Velua**

### CODE REVIEW

**Review by Ran73Cohen — COMMENTED** [review]
Balances are not being set
image

Build failed for some reason

**Comment by Velua** [comment]
@Ran73Cohen works on the staging for me, not sure if it's rebuilt then for my 3a43074 commit but should also work for network changes.

**Comment by Ran73Cohen** [comment]
Still too many emissions,
Login
Go to kovan
Switch back to mainnet

image

**Comment by Velua** [comment]
@Ran73Cohen looks like the currentNetworkReceiver$ was still getting passed unspported networks, I've since filtered that out and can work out a strategy further whether it's only supported networks go through there or another is built off of it called ```supportedNetwork$``` or something but probably won't be required.

**Pull request merged**
